#!/usr/bin/env bash
# Compare upstream BSI resolved catalog to local catalog.json.
# On change: commit on SYNC_BRANCH and open/update a PR against develop.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

# shellcheck source=/dev/null
source "$ROOT/upstream.env"
# shellcheck source=/dev/null
source "$ROOT/config.env"

: "${UPSTREAM_REPO:?}"
: "${UPSTREAM_PATH:?}"
: "${UPSTREAM_REF:?}"
: "${LOCAL_CATALOG:?}"
: "${SYNC_BRANCH:?}"

ENCODED_PATH="${UPSTREAM_PATH//+/%2B}"
RAW_URL="https://raw.githubusercontent.com/${UPSTREAM_REPO}/${UPSTREAM_REF}/${ENCODED_PATH}"
UPSTREAM_BLOB_URL="https://github.com/${UPSTREAM_REPO}/blob/${UPSTREAM_REF}/${ENCODED_PATH}"

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

curl -fsSL -o "$TMP" "$RAW_URL"

if [[ ! -f "$LOCAL_CATALOG" ]]; then
  echo "Missing local catalog: $LOCAL_CATALOG" >&2
  exit 1
fi

LOCAL_HASH="$(sha256sum "$LOCAL_CATALOG" | awk '{print $1}')"
UPSTREAM_HASH="$(sha256sum "$TMP" | awk '{print $1}')"

if [[ "$LOCAL_HASH" == "$UPSTREAM_HASH" ]]; then
  echo "Upstream catalog unchanged (sha256=${LOCAL_HASH:0:12})."
  exit 0
fi

echo "Catalog drift detected: local=${LOCAL_HASH:0:12} upstream=${UPSTREAM_HASH:0:12}"

PATH_QUERY="$(python3 -c "import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1], safe='/'))" "$UPSTREAM_PATH")"
CURL_AUTH=()
if [[ -n "${GITHUB_TOKEN:-}" ]]; then
  CURL_AUTH=(-H "Authorization: Bearer ${GITHUB_TOKEN}")
fi
UPSTREAM_COMMIT=""
if COMMITS_JSON="$(
  curl -fsSL \
    -H "Accept: application/vnd.github+json" \
    -H "User-Agent: rh-catalog-upstream-watch" \
    "${CURL_AUTH[@]}" \
    "https://api.github.com/repos/${UPSTREAM_REPO}/commits?path=${PATH_QUERY}&sha=${UPSTREAM_REF}&per_page=1"
)"; then
  UPSTREAM_COMMIT="$(
    python3 -c "import json,sys; data=json.load(sys.stdin); print(data[0]['sha'] if data else '')" <<<"$COMMITS_JSON"
  )" || UPSTREAM_COMMIT=""
fi

readarray -t META < <(python3 -c '
import json, sys
with open(sys.argv[1], encoding="utf-8") as f:
    cat = json.load(f)["catalog"]
md = cat["metadata"]
print(cat.get("uuid", ""))
print(md.get("last-modified", ""))
print(md.get("version", ""))
' "$TMP")
CATALOG_UUID="${META[0]:-}"
CATALOG_LAST_MODIFIED="${META[1]:-}"
CATALOG_VERSION="${META[2]:-}"

git config user.email "${EMAIL:-compliance.trestle@pleasedonotuse.win}"
git config user.name "${NAME:-Automation-Bot}"

git fetch origin develop "$SYNC_BRANCH" 2>/dev/null || git fetch origin develop

if gh pr list -H "$SYNC_BRANCH" -B develop --state open --json number -q '.[0].number' | grep -q .; then
  git checkout -B "$SYNC_BRANCH" "origin/$SYNC_BRANCH"
else
  git checkout -B "$SYNC_BRANCH" origin/develop
fi

cp "$TMP" "$LOCAL_CATALOG"
git add "$LOCAL_CATALOG"

if [[ -z "$(git status --porcelain)" ]]; then
  echo "Nothing to commit after copy (branch already in sync)."
  exit 0
fi

COMMIT_TITLE="chore: Sync Grundschutz++ catalog from upstream"
COMMIT_BODY="$(cat <<EOF
Sync ${LOCAL_CATALOG} from upstream.

- Upstream: ${UPSTREAM_BLOB_URL}
- Upstream commit: ${UPSTREAM_COMMIT:-unknown}
- Catalog uuid: ${CATALOG_UUID}
- Catalog last-modified: ${CATALOG_LAST_MODIFIED}
- Catalog version: ${CATALOG_VERSION}

Markdown under md_catalogs/ is regenerated by the develop push workflow after merge.
EOF
)"

git commit -m "$COMMIT_TITLE" -m "$COMMIT_BODY"

REMOTE=origin
if [[ -n "${GIT_TOKEN:-}" ]]; then
  REMOTE="${URL_CATALOG}"
fi

if gh pr list -H "$SYNC_BRANCH" -B develop --state open --json number -q '.[0].number' | grep -q .; then
  git push -u "$REMOTE" "$SYNC_BRANCH"
  echo "Updated existing open PR on $SYNC_BRANCH"
else
  git push -u --force-with-lease "$REMOTE" "$SYNC_BRANCH"
  gh pr create -t "$COMMIT_TITLE" -b "$COMMIT_BODY" -B develop -H "$SYNC_BRANCH"
  echo "Created PR from $SYNC_BRANCH to develop"
fi
